version: 2.1
commands: # a reusable command with parameters
  setup:
    parameters:
      version:
        default: "7.4"
        type: string
    steps:
      - checkout
      - run:
          # Our primary container isn't Nginx so run a sleep command until it's ready.
          name: Waiting for Nginx to be ready
          command: |
            /bin/app/start.sh &
            for i in `seq 1 100`;
            do
              nc -z 127.0.0.1 80 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Nginx && exit 1
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 100`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          # Our primary container isn't Elasticsearch so run a sleep command until it's ready.
          name: Waiting for Elasticsearch to be ready
          command: |
            for i in `seq 1 100`;
            do
              nc -z 127.0.0.1 9200 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          # Our primary container isn't Selenium so run a sleep command until it's ready.
          name: Waiting for Selenium to be ready
          command: |
            for i in `seq 1 100`;
            do
              nc -z 127.0.0.1 4444 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Selenium && exit 1
      - run:
          name: "Install Magento 2"
          command: |
            cd /var/www/html
            /bin/app/magento2/install.sh
      - run:
          name: "Setup Tests Environment"
          command: |
            cd /var/www/html
            vendor/bin/mftf build:project --MAGENTO_BASE_URL=http://magento2.localhost/ --MAGENTO_BACKEND_NAME=admin --MAGENTO_ADMIN_USERNAME=admin --MAGENTO_ADMIN_PASSWORD=admin123
            sed -i 's/chromeOptions:/"goog:chromeOptions":/g' dev/tests/acceptance/tests/functional.suite.yml
            sed -i 's/"--disable-extensions",/"--disable-extensions","--no-sandbox", "--headless",/g' dev/tests/acceptance/tests/functional.suite.yml
  cs-tests:
    steps:
      - run:
         name: "Run PHP Copy/Paste Detector"
         command: |
           phpcpd --exclude Model/Payment/ --exclude vendor --exclude Test /var/www/html/app/code/Latitude/Payment
      - run:
         name: "PHP Mess Detector"
         command: |
          cd /var/www/html
           phpmd app/code/Latitude/Payment text /var/www/html/app/code/Latitude/Payment/phpmd.xml --exclude vendor/,Test/
      - run:
         name: "PHP CodeSniffer"
         command: |
            phpcs --config-set show_warnings 0
            phpcs --standard=Magento2 --extensions=php --ignore=*/vendor/,*/Test/ --colors -s -p -v /var/www/html/app/code/Latitude/Payment
      # - run:
      #    name: "Run Backward Compatibility Check"
      #    command: |
      #      vendor/bin/roave-backward-compatibility-check
  m2-tests:
    steps:
      - run:
          name: "Magento Default Functional Testing"
          command: |
            cd /var/www/html
            vendor/bin/mftf run:test StorefrontCustomerCheckoutTest -r
            vendor/bin/mftf run:test StorefrontGuestCheckoutTest -r
            allure generate dev/tests/acceptance/tests/_output/ -o dev/tests/acceptance/tests/_output/allure-report
      - run:
          name: "Magento Default Unit Testing"
          command: |
            cd /var/www/html
            vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist --testdox
            allure generate dev/tests/acceptance/tests/_output/ -o dev/tests/acceptance/tests/_output/allure-report
  lp-tests:
    steps:
      - run:
          name: "LatitudePay Functional Testing"
          command: |
            cd /var/www/html
            vendor/bin/mftf run:group latitudepay -r
      - run:
          name: "LatitudePay Unit Testing"
          command: |
            cd /var/www/html
            vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/Latitude/Payment/Test/Unit/ --testdox
            allure generate dev/tests/acceptance/tests/_output/ -o dev/tests/acceptance/tests/_output/allure-report
  artifacts:
    steps:
      - store_test_results:
          path: /var/www/html/dev/tests/acceptance/tests/_output/allure-report
      - store_artifacts:
          path: /var/www/html/dev/tests/acceptance/tests/_output/allure-report
jobs:
  php73-build:
    docker:
      - image: registry.gitlab.com/magebinary/docker-opensource-ecommerce:magento-2.4.2-php-7.3
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
        environment:
          - MYSQL_ROOT_HOST=%
          - PLATFORM=magento2
          - PLATFORM_VERSION=2.4.2
          - MYSQL_ROOT_PASSWORD=magento2
          - MYSQL_DATABASE=magento2
          - MYSQL_USER=magento2
          - MYSQL_PASSWORD=magento2
          - MYSQL_DB_HOST=127.0.0.1
          - ES_HOST=127.0.0.1
          - ES_PORT=9200
          - BASE_URL=magento2.localhost
          - INSTALL_SAMPLE_DATA=false
          - MAGENTO_ADMIN_FRONTNAME=admin
          - MAGENTO_ADMIN_FIRST_NAME=Admin
          - MAGENTO_ADMIN_LAST_NAME=Developer
          - MAGENTO_ADMIN_EMAIL=dev@magebinary.com
          - MAGENTO_ADMIN_USER=admin
          - MAGENTO_ADMIN_PASSWORD=admin123
          - MAGENTO_LOCALE=en_AU
          - MAGENTO_CURRENCY=AUD
          - MAGENTO_TIMEZONE=Pacific/Auckland
          - LATITUDE_API_PUBLIC_KEY=$LATITUDE_API_PUBLIC_KEY
          - LATITUDE_API_PRIVATE_KEY=$LATITUDE_API_PRIVATE_KEY
          - LATITUDE_USER_EMAIL=$LATITUDE_USER_EMAIL
          - LATITUDE_USER_PASSWORD=$LATITUDE_USER_PASSWORD
          - GENOAPAY_API_PUBLIC_KEY=$GENOAPAY_API_PUBLIC_KEY
          - GENOAPAY_API_PRIVATE_KEY=$GENOAPAY_API_PRIVATE_KEY
          - GENOAPAY_USER_EMAIL=$GENOAPAY_USER_EMAIL
          - GENOAPAY_USER_PASSWORD=$GENOAPAY_USER_PASSWORD
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ROOT_HOST=%
          - MYSQL_ROOT_PASSWORD=magento2
          - MYSQL_DATABASE=magento2
          - MYSQL_USER=magento2
          - MYSQL_PASSWORD=magento2
      - image: magento/magento-cloud-docker-elasticsearch:7.9-1.2.2
    working_directory: /var/www/html/app/code/Latitude/Payment
    steps:
      - setup:
          version: "7.3"
      - cs-tests
      - lp-tests
      - m2-tests
      - artifacts
  php74-build:
    docker:
      - image: registry.gitlab.com/magebinary/docker-opensource-ecommerce:magento-2.4.2-php-7.4
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
        environment:
          - MYSQL_ROOT_HOST=%
          - PLATFORM=magento2
          - PLATFORM_VERSION=2.4.2
          - MYSQL_ROOT_PASSWORD=magento2
          - MYSQL_DATABASE=magento2
          - MYSQL_USER=magento2
          - MYSQL_PASSWORD=magento2
          - MYSQL_DB_HOST=127.0.0.1
          - ES_HOST=127.0.0.1
          - ES_PORT=9200
          - BASE_URL=magento2.localhost
          - INSTALL_SAMPLE_DATA=false
          - MAGENTO_ADMIN_FRONTNAME=admin
          - MAGENTO_ADMIN_FIRST_NAME=Admin
          - MAGENTO_ADMIN_LAST_NAME=Developer
          - MAGENTO_ADMIN_EMAIL=dev@magebinary.com
          - MAGENTO_ADMIN_USER=admin
          - MAGENTO_ADMIN_PASSWORD=admin123
          - MAGENTO_LOCALE=en_AU
          - MAGENTO_CURRENCY=AUD
          - MAGENTO_TIMEZONE=Pacific/Auckland
          - LATITUDE_API_PUBLIC_KEY=$LATITUDE_API_PUBLIC_KEY
          - LATITUDE_API_PRIVATE_KEY=$LATITUDE_API_PRIVATE_KEY
          - LATITUDE_USER_EMAIL=$LATITUDE_USER_EMAIL
          - LATITUDE_USER_PASSWORD=$LATITUDE_USER_PASSWORD
          - GENOAPAY_API_PUBLIC_KEY=$GENOAPAY_API_PUBLIC_KEY
          - GENOAPAY_API_PRIVATE_KEY=$GENOAPAY_API_PRIVATE_KEY
          - GENOAPAY_USER_EMAIL=$GENOAPAY_USER_EMAIL
          - GENOAPAY_USER_PASSWORD=$GENOAPAY_USER_PASSWORD
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ROOT_HOST=%
          - MYSQL_ROOT_PASSWORD=magento2
          - MYSQL_DATABASE=magento2
          - MYSQL_USER=magento2
          - MYSQL_PASSWORD=magento2
      - image: magento/magento-cloud-docker-elasticsearch:7.9-1.2.2
    working_directory: /var/www/html/app/code/Latitude/Payment
    steps:
      - setup:
          version: "7.4"
      - cs-tests
      - lp-tests
      - m2-tests
      - artifacts
workflows:
  version: 2
  main:
    jobs:
      - php73-build
      - php74-build